### ISSUE TITLE
Download threads and speed

### ISSUE THREAD

**Issue by gabo77** [sylvainlehmann/s3ql#1]
Download speeds with B2 are much slower compared to those on GCS. Downloading a single file with rsync, max speeds are averaging at ~4Mbps on B2 and ~20Mbps on GCS. Also, with both B2 and GCS, stacking multiple rsync downloads won't slow down individual downloads and will just add up for a total speed of ~ 4*n on B2 and 20*n on GCS.

With that in mind, would there be anyway way to allow more download threads per file on B2 so it can reach comparable speeds? You'll find the output of netstat -an of different tests in the files linked, named netstat[backend][#rsync] (ie netstatb27 = 7 concurrent rsync downloads on b2)

[netstatb21.txt](https://github.com/sylvainlehmann/s3ql/files/1016491/netstatb21.txt)
[netstat.b27.txt](https://github.com/sylvainlehmann/s3ql/files/1016488/netstat.b27.txt)
[netstat.gcs1.txt](https://github.com/sylvainlehmann/s3ql/files/1016490/netstat.gcs1.txt)
[netstat.gcs2.txt](https://github.com/sylvainlehmann/s3ql/files/1016489/netstat.gcs2.txt)

**Comment by gabo77** [comment]
As per blackbaze support, single threaded download speeds will vary depending on the latency of the connection. But, we should be able to maintain 1 to 2 GB/s throughput given enough download threads.

I was wondering, are my results consistent with yours?

**Comment by sylvainlehmann** [comment]
S3ql cut each file in block of pre definied size (10mb by default). The backend only manage theses blocks, which are generaly too small for efficient parallel upload or download, and does not know the file they belong to. The only way to parrallel downloading one file is changing the s3ql file download algorithm. Unfortunalty this issue is more an s3ql issue than a backblaze backend one.
